---
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
env:
  - REMOVE_LOCALES=false
  - REMOVE_LOCALES=true
install:
  - pip install -r requirements.txt -r tests/requirements.txt
  - pip install .
  - if [[ $REMOVE_LOCALES = "true" ]]; then sudo rm -rf /usr/lib/locale/*; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then doc8 $(git ls-files '*.rst'); fi
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - coverage run --source=yamllint setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then
      python setup.py build_sphinx;
    fi
after_success:
  coveralls
